# Auto-generated by ewdk toolchain manager - DO NOT EDIT
# include(ewdk.cmake) provides WDK detection, compiler setup, and all wdk_* / um_* functions

# ---- WDK Core ----
set(WDK_FOUND TRUE)
set(WDK_ROOT "E:/Program Files/Windows Kits/10")
set(WDK_VERSION "10.0.28000.0")
set(WDK_INC_VERSION "10.0.28000.0")
set(WDK_LIB_VERSION "10.0.28000.0")
set(WDK_PLATFORM "x64")

# ---- KM (Kernel-Mode) ----
set(WDK_KM_INCLUDE_DIRS "E:/Program Files/Windows Kits/10/Include/10.0.28000.0/shared;E:/Program Files/Windows Kits/10/Include/10.0.28000.0/km;E:/Program Files/Windows Kits/10/Include/10.0.28000.0/km/crt;E:/Program Files/Windows Kits/10/Include/wdf/kmdf/1.35")
set(WDK_KM_LIB_DIRS "E:/Program Files/Windows Kits/10/Lib/10.0.28000.0/km/x64")

# ---- UM (User-Mode) ----
set(WDK_UM_INCLUDE_DIRS "E:/Program Files/Windows Kits/10/Include/10.0.28000.0/shared;E:/Program Files/Windows Kits/10/Include/10.0.28000.0/um;E:/Program Files/Windows Kits/10/Include/10.0.28000.0/ucrt;E:/Program Files/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.44.35207/include;E:/Program Files/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.44.35207/ATLMFC/include;E:/Program Files/Microsoft Visual Studio/2022/BuildTools/VC/Auxiliary/VS/include;E:/Program Files/Microsoft Visual Studio/2022/BuildTools/DIA SDK/include")
set(WDK_UM_LIB_DIRS "E:/Program Files/Windows Kits/10/Lib/10.0.28000.0/um/x64;E:/Program Files/Windows Kits/10/Lib/10.0.28000.0/ucrt/x64;E:/Program Files/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.44.35207/lib/x64;E:/Program Files/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.44.35207/ATLMFC/lib/x64;E:/Program Files/Microsoft Visual Studio/2022/BuildTools/DIA SDK/lib")

# ---- Compiler ----
set(CMAKE_C_COMPILER "E:/Program Files/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.44.35207/bin/Hostx64/x64/cl.exe" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "E:/Program Files/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.44.35207/bin/Hostx64/x64/cl.exe" CACHE FILEPATH "" FORCE)
set(CMAKE_RC_COMPILER "E:/Program Files/Windows Kits/10/bin/10.0.28000.0/x64/rc.exe" CACHE FILEPATH "" FORCE)
set(CMAKE_C_COMPILER_WORKS 1 CACHE INTERNAL "")
set(CMAKE_CXX_COMPILER_WORKS 1 CACHE INTERNAL "")
set(CMAKE_C_STANDARD_LIBRARIES "")
set(CMAKE_CXX_STANDARD_LIBRARIES "")
set(CMAKE_INCLUDE_PATH "${WDK_KM_INCLUDE_DIRS};${WDK_UM_INCLUDE_DIRS}" CACHE STRING "" FORCE)
set(CMAKE_LIBRARY_PATH "${WDK_KM_LIB_DIRS};${WDK_UM_LIB_DIRS}" CACHE STRING "" FORCE)
list(APPEND CMAKE_PROGRAM_PATH "D:/ewdk")
list(APPEND CMAKE_PROGRAM_PATH "E:/Program Files/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.44.35207/bin/Hostx64/x64")
list(APPEND CMAKE_PROGRAM_PATH "E:/Program Files/Windows Kits/10/bin/10.0.28000.0/x64")
set(CMAKE_MT "E:/Program Files/Windows Kits/10/bin/10.0.28000.0/x64/mt.exe" CACHE FILEPATH "" FORCE)

set(ENV{WDKContentRoot} "${WDK_ROOT}")
set(ENV{INCLUDE} "${WDK_KM_INCLUDE_DIRS};${WDK_UM_INCLUDE_DIRS}")
set(ENV{LIB} "${WDK_KM_LIB_DIRS};${WDK_UM_LIB_DIRS}")

# ---- WDK Settings ----
set(WDK_WINVER "0x0601" CACHE STRING "Default WINVER for WDK targets")
set(WDK_NTDDI_VERSION "" CACHE STRING "Specified NTDDI_VERSION for WDK targets if needed")
if(DEFINED ENV{GITHUB_ACTIONS})
    set(KM_TEST_SIGN OFF CACHE BOOL "Enable test signing for drivers (disabled in CI)")
else()
    set(KM_TEST_SIGN ON CACHE BOOL "Enable test signing for drivers")
endif()
set(KM_TEST_SIGN_NAME "WDKTestCert" CACHE STRING "Certificate name for test signing")

set(KM_ADDITIONAL_FLAGS_FILE "${CMAKE_CURRENT_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/wdkflags.h")
file(WRITE ${KM_ADDITIONAL_FLAGS_FILE} "#pragma runtime_checks(\"suc\", off)")

set(KM_COMPILE_FLAGS
    "/Zp8"
    "/GF"
    "/GR-"
    "/Gz"
    "/kernel"
    "/FIwarning.h"
    "/FI${KM_ADDITIONAL_FLAGS_FILE}"
    "/Oi"
    )

set(KM_COMPILE_DEFINITIONS "WINNT=1;_AMD64_;AMD64")
set(KM_COMPILE_DEFINITIONS_DEBUG "MSC_NOOPT;DEPRECATE_DDK_FUNCTIONS=1;DBG=1")

string(CONCAT KM_LINK_FLAGS
    "/MANIFEST:NO "
    "/DRIVER "
    "/OPT:REF "
    "/INCREMENTAL:NO "
    "/OPT:ICF "
    "/SUBSYSTEM:NATIVE "
    "/ENTRY:DriverEntry "
    "/MERGE:_TEXT=.text;_PAGE=PAGE "
    "/NODEFAULTLIB "
    "/SECTION:INIT,d "
    "/VERSION:10.0 "
    )

# ---- KM Libraries ----
file(GLOB KM_LIB_FILES "E:/Program Files/Windows Kits/10/Lib/10.0.28000.0/km/x64/*.lib")
foreach(LIB_FILE ${KM_LIB_FILES})
    get_filename_component(LIB_NAME ${LIB_FILE} NAME_WE)
    string(TOUPPER ${LIB_NAME} LIB_NAME)
    add_library(WDK::${LIB_NAME} INTERFACE IMPORTED)
    set_property(TARGET WDK::${LIB_NAME} PROPERTY INTERFACE_LINK_LIBRARIES ${LIB_FILE})
endforeach()

set(KM_SIGNTOOL_PATH "E:/Program Files/Windows Kits/10/bin/10.0.28000.0/x64/signtool.exe")


# ---- KM/UM Functions ----

function(km_sys _target)
    cmake_parse_arguments(WDK "" "KMDF;WINVER;NTDDI_VERSION" "" ${ARGN})

    add_executable(${_target} ${WDK_UNPARSED_ARGUMENTS})

    set_target_properties(${_target} PROPERTIES SUFFIX ".sys")
    set_target_properties(${_target} PROPERTIES COMPILE_OPTIONS "${KM_COMPILE_FLAGS}")
    set_target_properties(${_target} PROPERTIES COMPILE_DEFINITIONS
        "${KM_COMPILE_DEFINITIONS};$<$<CONFIG:Debug>:${KM_COMPILE_DEFINITIONS_DEBUG}>;_WIN32_WINNT=${WDK_WINVER}"
        )
    set_target_properties(${_target} PROPERTIES LINK_FLAGS "${KM_LINK_FLAGS}")
    set_target_properties(${_target} PROPERTIES LINK_INTERFACE_LIBRARIES "")
    if(WDK_NTDDI_VERSION)
        target_compile_definitions(${_target} PRIVATE NTDDI_VERSION=${WDK_NTDDI_VERSION})
    endif()

    target_include_directories(${_target} PRIVATE ${WDK_KM_INCLUDE_DIRS})

    target_link_libraries(${_target} WDK::NTOSKRNL WDK::HAL WDK::WMILIB)

    if(WDK::BUFFEROVERFLOWK)
        target_link_libraries(${_target} WDK::BUFFEROVERFLOWK)
    else()
        target_link_libraries(${_target} WDK::BUFFEROVERFLOWFASTFAILK)
    endif()

    if(DEFINED WDK_KMDF)
        target_include_directories(${_target} PRIVATE "${WDK_ROOT}/Include/wdf/kmdf/${WDK_KMDF}")
        target_link_libraries(${_target}
            "${WDK_ROOT}/Lib/wdf/kmdf/${WDK_PLATFORM}/${WDK_KMDF}/WdfDriverEntry.lib"
            "${WDK_ROOT}/Lib/wdf/kmdf/${WDK_PLATFORM}/${WDK_KMDF}/WdfLdr.lib"
            )
        set_property(TARGET ${_target} APPEND_STRING PROPERTY LINK_FLAGS "/ENTRY:FxDriverEntry")
    else()
        set_property(TARGET ${_target} APPEND_STRING PROPERTY LINK_FLAGS "/ENTRY:GsDriverEntry")
    endif()

    if(KM_TEST_SIGN AND DEFINED KM_SIGNTOOL_PATH)
        add_custom_command(TARGET ${_target} POST_BUILD
            COMMAND ${KM_SIGNTOOL_PATH} sign /fd SHA256 /s My /n ${KM_TEST_SIGN_NAME} /t http://timestamp.digicert.com $<TARGET_FILE:${_target}>
            WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
            COMMENT "Signing driver with test certificate: ${KM_TEST_SIGN_NAME}"
            VERBATIM
        )
    endif()
endfunction()

function(km_lib _target)
    cmake_parse_arguments(WDK "" "KMDF;WINVER;NTDDI_VERSION" "" ${ARGN})

    add_library(${_target} ${WDK_UNPARSED_ARGUMENTS})

    set_target_properties(${_target} PROPERTIES COMPILE_OPTIONS "${KM_COMPILE_FLAGS}")
    set_target_properties(${_target} PROPERTIES COMPILE_DEFINITIONS
        "${KM_COMPILE_DEFINITIONS};$<$<CONFIG:Debug>:${KM_COMPILE_DEFINITIONS_DEBUG};>_WIN32_WINNT=${WDK_WINVER}"
        )
    if(WDK_NTDDI_VERSION)
        target_compile_definitions(${_target} PRIVATE NTDDI_VERSION=${WDK_NTDDI_VERSION})
    endif()

    target_include_directories(${_target} PRIVATE ${WDK_KM_INCLUDE_DIRS})

    if(DEFINED WDK_KMDF)
        target_include_directories(${_target} PRIVATE "${WDK_ROOT}/Include/wdf/kmdf/${WDK_KMDF}")
    endif()
endfunction()

function(um_exe _target)
    cmake_parse_arguments(WDK "" "SUBSYSTEM;WINVER;NTDDI_VERSION" "" ${ARGN})

    if(NOT WDK_SUBSYSTEM)
        set(WDK_SUBSYSTEM "CONSOLE")
    endif()

    add_executable(${_target} ${WDK_UNPARSED_ARGUMENTS})

    string(TOUPPER "${WDK_SUBSYSTEM}" _subsystem_upper)

    set_target_properties(${_target} PROPERTIES COMPILE_DEFINITIONS "_WIN32_WINNT=${WDK_WINVER}")
    set_target_properties(${_target} PROPERTIES MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")

    if(WDK_NTDDI_VERSION)
        target_compile_definitions(${_target} PRIVATE NTDDI_VERSION=${WDK_NTDDI_VERSION})
    endif()

    target_include_directories(${_target} PRIVATE ${WDK_UM_INCLUDE_DIRS})

    if(_subsystem_upper STREQUAL "CONSOLE" OR _subsystem_upper STREQUAL "WINCON")
        set_target_properties(${_target} PROPERTIES LINK_FLAGS "/SUBSYSTEM:CONSOLE")
    elseif(_subsystem_upper STREQUAL "WINDOWS" OR _subsystem_upper STREQUAL "WIN")
        set_target_properties(${_target} PROPERTIES LINK_FLAGS "/SUBSYSTEM:WINDOWS")
    endif()

    foreach(_lib_dir ${WDK_UM_LIB_DIRS})
        target_link_options(${_target} PRIVATE "/LIBPATH:${_lib_dir}")
    endforeach()
    target_link_libraries(${_target} kernel32.lib user32.lib)
endfunction()

function(um_lib _target)
    cmake_parse_arguments(WDK "" "WINVER;NTDDI_VERSION" "" ${ARGN})

    add_library(${_target} ${WDK_UNPARSED_ARGUMENTS})

    set_target_properties(${_target} PROPERTIES COMPILE_DEFINITIONS "_WIN32_WINNT=${WDK_WINVER}")
    set_target_properties(${_target} PROPERTIES MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")

    if(WDK_NTDDI_VERSION)
        target_compile_definitions(${_target} PRIVATE NTDDI_VERSION=${WDK_NTDDI_VERSION})
    endif()

    target_include_directories(${_target} PRIVATE ${WDK_UM_INCLUDE_DIRS})
    foreach(_lib_dir ${WDK_UM_LIB_DIRS})
        target_link_options(${_target} PRIVATE "/LIBPATH:${_lib_dir}")
    endforeach()
endfunction()

function(um_dll _target)
    cmake_parse_arguments(WDK "" "WINVER;NTDDI_VERSION" "" ${ARGN})

    add_library(${_target} SHARED ${WDK_UNPARSED_ARGUMENTS})

    set_target_properties(${_target} PROPERTIES COMPILE_DEFINITIONS
        "_WIN32_WINNT=${WDK_WINVER};_USRDLL;_WINDLL"
        )
    set_target_properties(${_target} PROPERTIES MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")

    if(WDK_NTDDI_VERSION)
        target_compile_definitions(${_target} PRIVATE NTDDI_VERSION=${WDK_NTDDI_VERSION})
    endif()

    target_include_directories(${_target} PRIVATE ${WDK_UM_INCLUDE_DIRS})
    foreach(_lib_dir ${WDK_UM_LIB_DIRS})
        target_link_options(${_target} PRIVATE "/LIBPATH:${_lib_dir}")
    endforeach()
    target_link_libraries(${_target} kernel32.lib)
endfunction()
