#pragma once
#ifndef MIQT_QT6_GEN_QWIDGET_H
#define MIQT_QT6_GEN_QWIDGET_H




#include "libmiqt.h"
#include "miqt_export.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAction;
class QActionEvent;
class QBackingStore;
class QBitmap;
class QChildEvent;
class QCloseEvent;
class QContextMenuEvent;
class QCursor;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEnterEvent;
class QEvent;
class QFocusEvent;
class QFont;
class QFontInfo;
class QFontMetrics;
class QGraphicsEffect;
class QGraphicsProxyWidget;
class QHideEvent;
class QIcon;
class QInputMethodEvent;
class QKeyEvent;
class QKeySequence;
class QLayout;
class QLocale;
class QMargins;
class QMetaMethod;
class QMetaObject;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPalette;
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QPalette__ColorRole)
typedef QPalette::ColorRole QPalette__ColorRole;
#else
class QPalette__ColorRole;
#endif
class QPixmap;
class QPoint;
class QPointF;
class QRect;
class QRegion;
class QResizeEvent;
class QScreen;
class QShowEvent;
class QSize;
class QSizePolicy;
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QSizePolicy__Policy)
typedef QSizePolicy::Policy QSizePolicy__Policy;
#else
class QSizePolicy__Policy;
#endif
class QStyle;
class QTabletEvent;
class QTimerEvent;
class QVariant;
class QWheelEvent;
class QWidget;
class QWindow;
using Qt_WindowFlags = Qt::WindowFlags;
using Qt_WindowModality = Qt::WindowModality;
using Qt_GestureType = Qt::GestureType;
using Qt_LayoutDirection = Qt::LayoutDirection;
using Qt_FocusReason = Qt::FocusReason;
using Qt_FocusPolicy = Qt::FocusPolicy;
using Qt_ContextMenuPolicy = Qt::ContextMenuPolicy;
using Qt_WindowStates = Qt::WindowStates;
using Qt_WindowType = Qt::WindowType;
using Qt_WidgetAttribute = Qt::WidgetAttribute;
using Qt_InputMethodQuery = Qt::InputMethodQuery;
using Qt_InputMethodHints = Qt::InputMethodHints;
using Qt_GestureFlags = Qt::GestureFlags;
using Qt_ShortcutContext = Qt::ShortcutContext;
#else
typedef struct QAction QAction;
typedef struct QActionEvent QActionEvent;
typedef struct QBackingStore QBackingStore;
typedef struct QBitmap QBitmap;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QCursor QCursor;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFont QFont;
typedef struct QFontInfo QFontInfo;
typedef struct QFontMetrics QFontMetrics;
typedef struct QGraphicsEffect QGraphicsEffect;
typedef struct QGraphicsProxyWidget QGraphicsProxyWidget;
typedef struct QHideEvent QHideEvent;
typedef struct QIcon QIcon;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QKeySequence QKeySequence;
typedef struct QLayout QLayout;
typedef struct QLocale QLocale;
typedef struct QMargins QMargins;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPalette QPalette;
typedef struct QPalette__ColorRole QPalette__ColorRole;
typedef struct QPixmap QPixmap;
typedef struct QPoint QPoint;
typedef struct QPointF QPointF;
typedef struct QRect QRect;
typedef struct QRegion QRegion;
typedef struct QResizeEvent QResizeEvent;
typedef struct QScreen QScreen;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QSizePolicy QSizePolicy;
typedef struct QSizePolicy__Policy QSizePolicy__Policy;
typedef struct QStyle QStyle;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct QWindow QWindow;
typedef int Qt_WindowFlags;
typedef int Qt_WindowModality;
typedef int Qt_GestureType;
typedef int Qt_LayoutDirection;
typedef int Qt_FocusReason;
typedef int Qt_FocusPolicy;
typedef int Qt_ContextMenuPolicy;
typedef int Qt_WindowStates;
typedef int Qt_WindowType;
typedef int Qt_WidgetAttribute;
typedef int Qt_InputMethodQuery;
typedef int Qt_InputMethodHints;
typedef int Qt_GestureFlags;
typedef int Qt_ShortcutContext;
#endif

MIQT_EXPORT QWidget*QWidget_new(QWidget*parent);
MIQT_EXPORT QWidget*QWidget_new2();
MIQT_EXPORT QWidget*QWidget_new3(QWidget*parent, Qt_WindowFlags f);
MIQT_EXPORT void QWidget_virtbase(QWidget*src, QObject** outptr_QObject, QPaintDevice** outptr_QPaintDevice);
MIQT_EXPORT QMetaObject*QWidget_metaObject(QWidget*self);
MIQT_EXPORT void*QWidget_metacast(QWidget*self, char*param1);
MIQT_EXPORT struct miqt_string QWidget_tr(char*s);
MIQT_EXPORT int QWidget_devType(QWidget*self);
MIQT_EXPORT WId QWidget_winId(QWidget*self);
MIQT_EXPORT void QWidget_createWinId(QWidget*self);
MIQT_EXPORT WId QWidget_internalWinId(QWidget*self);
MIQT_EXPORT WId QWidget_effectiveWinId(QWidget*self);
MIQT_EXPORT QStyle*QWidget_style(QWidget*self);
MIQT_EXPORT void QWidget_setStyle(QWidget*self, QStyle*style);
MIQT_EXPORT bool QWidget_isTopLevel(QWidget*self);
MIQT_EXPORT bool QWidget_isWindow(QWidget*self);
MIQT_EXPORT bool QWidget_isModal(QWidget*self);
MIQT_EXPORT Qt_WindowModality QWidget_windowModality(QWidget*self);
MIQT_EXPORT void QWidget_setWindowModality(QWidget*self, Qt_WindowModality windowModality);
MIQT_EXPORT bool QWidget_isEnabled(QWidget*self);
MIQT_EXPORT bool QWidget_isEnabledTo(QWidget*self, QWidget*param1);
MIQT_EXPORT void QWidget_setEnabled(QWidget*self, bool enabled);
MIQT_EXPORT void QWidget_setDisabled(QWidget*self, bool disabled);
MIQT_EXPORT void QWidget_setWindowModified(QWidget*self, bool windowModified);
MIQT_EXPORT QRect*QWidget_frameGeometry(QWidget*self);
MIQT_EXPORT QRect*QWidget_geometry(QWidget*self);
MIQT_EXPORT QRect*QWidget_normalGeometry(QWidget*self);
MIQT_EXPORT int QWidget_x(QWidget*self);
MIQT_EXPORT int QWidget_y(QWidget*self);
MIQT_EXPORT QPoint*QWidget_pos(QWidget*self);
MIQT_EXPORT QSize*QWidget_frameSize(QWidget*self);
MIQT_EXPORT QSize*QWidget_size(QWidget*self);
MIQT_EXPORT int QWidget_width(QWidget*self);
MIQT_EXPORT int QWidget_height(QWidget*self);
MIQT_EXPORT QRect*QWidget_rect(QWidget*self);
MIQT_EXPORT QRect*QWidget_childrenRect(QWidget*self);
MIQT_EXPORT QRegion*QWidget_childrenRegion(QWidget*self);
MIQT_EXPORT QSize*QWidget_minimumSize(QWidget*self);
MIQT_EXPORT QSize*QWidget_maximumSize(QWidget*self);
MIQT_EXPORT int QWidget_minimumWidth(QWidget*self);
MIQT_EXPORT int QWidget_minimumHeight(QWidget*self);
MIQT_EXPORT int QWidget_maximumWidth(QWidget*self);
MIQT_EXPORT int QWidget_maximumHeight(QWidget*self);
MIQT_EXPORT void QWidget_setMinimumSize(QWidget*self, QSize*minimumSize);
MIQT_EXPORT void QWidget_setMinimumSize2(QWidget*self, int minw, int minh);
MIQT_EXPORT void QWidget_setMaximumSize(QWidget*self, QSize*maximumSize);
MIQT_EXPORT void QWidget_setMaximumSize2(QWidget*self, int maxw, int maxh);
MIQT_EXPORT void QWidget_setMinimumWidth(QWidget*self, int minw);
MIQT_EXPORT void QWidget_setMinimumHeight(QWidget*self, int minh);
MIQT_EXPORT void QWidget_setMaximumWidth(QWidget*self, int maxw);
MIQT_EXPORT void QWidget_setMaximumHeight(QWidget*self, int maxh);
MIQT_EXPORT QSize*QWidget_sizeIncrement(QWidget*self);
MIQT_EXPORT void QWidget_setSizeIncrement(QWidget*self, QSize*sizeIncrement);
MIQT_EXPORT void QWidget_setSizeIncrement2(QWidget*self, int w, int h);
MIQT_EXPORT QSize*QWidget_baseSize(QWidget*self);
MIQT_EXPORT void QWidget_setBaseSize(QWidget*self, QSize*baseSize);
MIQT_EXPORT void QWidget_setBaseSize2(QWidget*self, int basew, int baseh);
MIQT_EXPORT void QWidget_setFixedSize(QWidget*self, QSize*fixedSize);
MIQT_EXPORT void QWidget_setFixedSize2(QWidget*self, int w, int h);
MIQT_EXPORT void QWidget_setFixedWidth(QWidget*self, int w);
MIQT_EXPORT void QWidget_setFixedHeight(QWidget*self, int h);
MIQT_EXPORT QPointF*QWidget_mapToGlobal(QWidget*self, QPointF*param1);
MIQT_EXPORT QPoint*QWidget_mapToGlobalWithQPoint(QWidget*self, QPoint*param1);
MIQT_EXPORT QPointF*QWidget_mapFromGlobal(QWidget*self, QPointF*param1);
MIQT_EXPORT QPoint*QWidget_mapFromGlobalWithQPoint(QWidget*self, QPoint*param1);
MIQT_EXPORT QPointF*QWidget_mapToParent(QWidget*self, QPointF*param1);
MIQT_EXPORT QPoint*QWidget_mapToParentWithQPoint(QWidget*self, QPoint*param1);
MIQT_EXPORT QPointF*QWidget_mapFromParent(QWidget*self, QPointF*param1);
MIQT_EXPORT QPoint*QWidget_mapFromParentWithQPoint(QWidget*self, QPoint*param1);
MIQT_EXPORT QPointF*QWidget_mapTo(QWidget*self, QWidget*param1, QPointF*param2);
MIQT_EXPORT QPoint*QWidget_mapTo2(QWidget*self, QWidget*param1, QPoint*param2);
MIQT_EXPORT QPointF*QWidget_mapFrom(QWidget*self, QWidget*param1, QPointF*param2);
MIQT_EXPORT QPoint*QWidget_mapFrom2(QWidget*self, QWidget*param1, QPoint*param2);
MIQT_EXPORT QWidget*QWidget_window(QWidget*self);
MIQT_EXPORT QWidget*QWidget_nativeParentWidget(QWidget*self);
MIQT_EXPORT QWidget*QWidget_topLevelWidget(QWidget*self);
MIQT_EXPORT QPalette*QWidget_palette(QWidget*self);
MIQT_EXPORT void QWidget_setPalette(QWidget*self, QPalette*palette);
MIQT_EXPORT void QWidget_setBackgroundRole(QWidget*self, QPalette__ColorRole*backgroundRole);
MIQT_EXPORT QPalette__ColorRole*QWidget_backgroundRole(QWidget*self);
MIQT_EXPORT void QWidget_setForegroundRole(QWidget*self, QPalette__ColorRole*foregroundRole);
MIQT_EXPORT QPalette__ColorRole*QWidget_foregroundRole(QWidget*self);
MIQT_EXPORT QFont*QWidget_font(QWidget*self);
MIQT_EXPORT void QWidget_setFont(QWidget*self, QFont*font);
MIQT_EXPORT QFontMetrics*QWidget_fontMetrics(QWidget*self);
MIQT_EXPORT QFontInfo*QWidget_fontInfo(QWidget*self);
MIQT_EXPORT QCursor*QWidget_cursor(QWidget*self);
MIQT_EXPORT void QWidget_setCursor(QWidget*self, QCursor*cursor);
MIQT_EXPORT void QWidget_unsetCursor(QWidget*self);
MIQT_EXPORT void QWidget_setMouseTracking(QWidget*self, bool enable);
MIQT_EXPORT bool QWidget_hasMouseTracking(QWidget*self);
MIQT_EXPORT bool QWidget_underMouse(QWidget*self);
MIQT_EXPORT void QWidget_setTabletTracking(QWidget*self, bool enable);
MIQT_EXPORT bool QWidget_hasTabletTracking(QWidget*self);
MIQT_EXPORT void QWidget_setMask(QWidget*self, QBitmap*mask);
MIQT_EXPORT void QWidget_setMaskWithMask(QWidget*self, QRegion*mask);
MIQT_EXPORT QRegion*QWidget_mask(QWidget*self);
MIQT_EXPORT void QWidget_clearMask(QWidget*self);
MIQT_EXPORT void QWidget_render(QWidget*self, QPaintDevice*target);
MIQT_EXPORT void QWidget_renderWithPainter(QWidget*self, QPainter*painter);
MIQT_EXPORT QPixmap*QWidget_grab(QWidget*self);
MIQT_EXPORT QGraphicsEffect*QWidget_graphicsEffect(QWidget*self);
MIQT_EXPORT void QWidget_setGraphicsEffect(QWidget*self, QGraphicsEffect*effect);
MIQT_EXPORT void QWidget_grabGesture(QWidget*self, Qt_GestureType type);
MIQT_EXPORT void QWidget_ungrabGesture(QWidget*self, Qt_GestureType type);
MIQT_EXPORT void QWidget_setWindowTitle(QWidget*self, struct miqt_string windowTitle);
MIQT_EXPORT void QWidget_setStyleSheet(QWidget*self, struct miqt_string styleSheet);
MIQT_EXPORT struct miqt_string QWidget_styleSheet(QWidget*self);
MIQT_EXPORT struct miqt_string QWidget_windowTitle(QWidget*self);
MIQT_EXPORT void QWidget_setWindowIcon(QWidget*self, QIcon*icon);
MIQT_EXPORT QIcon*QWidget_windowIcon(QWidget*self);
MIQT_EXPORT void QWidget_setWindowIconText(QWidget*self, struct miqt_string windowIconText);
MIQT_EXPORT struct miqt_string QWidget_windowIconText(QWidget*self);
MIQT_EXPORT void QWidget_setWindowRole(QWidget*self, struct miqt_string windowRole);
MIQT_EXPORT struct miqt_string QWidget_windowRole(QWidget*self);
MIQT_EXPORT void QWidget_setWindowFilePath(QWidget*self, struct miqt_string filePath);
MIQT_EXPORT struct miqt_string QWidget_windowFilePath(QWidget*self);
MIQT_EXPORT void QWidget_setWindowOpacity(QWidget*self, double level);
MIQT_EXPORT double QWidget_windowOpacity(QWidget*self);
MIQT_EXPORT bool QWidget_isWindowModified(QWidget*self);
MIQT_EXPORT void QWidget_setToolTip(QWidget*self, struct miqt_string toolTip);
MIQT_EXPORT struct miqt_string QWidget_toolTip(QWidget*self);
MIQT_EXPORT void QWidget_setToolTipDuration(QWidget*self, int msec);
MIQT_EXPORT int QWidget_toolTipDuration(QWidget*self);
MIQT_EXPORT void QWidget_setStatusTip(QWidget*self, struct miqt_string statusTip);
MIQT_EXPORT struct miqt_string QWidget_statusTip(QWidget*self);
MIQT_EXPORT void QWidget_setWhatsThis(QWidget*self, struct miqt_string whatsThis);
MIQT_EXPORT struct miqt_string QWidget_whatsThis(QWidget*self);
MIQT_EXPORT struct miqt_string QWidget_accessibleName(QWidget*self);
MIQT_EXPORT void QWidget_setAccessibleName(QWidget*self, struct miqt_string name);
MIQT_EXPORT struct miqt_string QWidget_accessibleDescription(QWidget*self);
MIQT_EXPORT void QWidget_setAccessibleDescription(QWidget*self, struct miqt_string description);
MIQT_EXPORT struct miqt_string QWidget_accessibleIdentifier(QWidget*self);
MIQT_EXPORT void QWidget_setAccessibleIdentifier(QWidget*self, struct miqt_string identifier);
MIQT_EXPORT void QWidget_setLayoutDirection(QWidget*self, Qt_LayoutDirection direction);
MIQT_EXPORT Qt_LayoutDirection QWidget_layoutDirection(QWidget*self);
MIQT_EXPORT void QWidget_unsetLayoutDirection(QWidget*self);
MIQT_EXPORT void QWidget_setLocale(QWidget*self, QLocale*locale);
MIQT_EXPORT QLocale*QWidget_locale(QWidget*self);
MIQT_EXPORT void QWidget_unsetLocale(QWidget*self);
MIQT_EXPORT bool QWidget_isRightToLeft(QWidget*self);
MIQT_EXPORT bool QWidget_isLeftToRight(QWidget*self);
MIQT_EXPORT void QWidget_setFocus(QWidget*self);
MIQT_EXPORT bool QWidget_isActiveWindow(QWidget*self);
MIQT_EXPORT void QWidget_activateWindow(QWidget*self);
MIQT_EXPORT void QWidget_clearFocus(QWidget*self);
MIQT_EXPORT void QWidget_setFocusWithReason(QWidget*self, Qt_FocusReason reason);
MIQT_EXPORT Qt_FocusPolicy QWidget_focusPolicy(QWidget*self);
MIQT_EXPORT void QWidget_setFocusPolicy(QWidget*self, Qt_FocusPolicy policy);
MIQT_EXPORT bool QWidget_hasFocus(QWidget*self);
MIQT_EXPORT void QWidget_setTabOrder(QWidget*param1, QWidget*param2);
MIQT_EXPORT void QWidget_setFocusProxy(QWidget*self, QWidget*focusProxy);
MIQT_EXPORT QWidget*QWidget_focusProxy(QWidget*self);
MIQT_EXPORT Qt_ContextMenuPolicy QWidget_contextMenuPolicy(QWidget*self);
MIQT_EXPORT void QWidget_setContextMenuPolicy(QWidget*self, Qt_ContextMenuPolicy policy);
MIQT_EXPORT void QWidget_grabMouse(QWidget*self);
MIQT_EXPORT void QWidget_grabMouseWithQCursor(QWidget*self, QCursor*param1);
MIQT_EXPORT void QWidget_releaseMouse(QWidget*self);
MIQT_EXPORT void QWidget_grabKeyboard(QWidget*self);
MIQT_EXPORT void QWidget_releaseKeyboard(QWidget*self);
MIQT_EXPORT int QWidget_grabShortcut(QWidget*self, QKeySequence*key);
MIQT_EXPORT void QWidget_releaseShortcut(QWidget*self, int id);
MIQT_EXPORT void QWidget_setShortcutEnabled(QWidget*self, int id);
MIQT_EXPORT void QWidget_setShortcutAutoRepeat(QWidget*self, int id);
MIQT_EXPORT QWidget*QWidget_mouseGrabber();
MIQT_EXPORT QWidget*QWidget_keyboardGrabber();
MIQT_EXPORT bool QWidget_updatesEnabled(QWidget*self);
MIQT_EXPORT void QWidget_setUpdatesEnabled(QWidget*self, bool enable);
MIQT_EXPORT QGraphicsProxyWidget*QWidget_graphicsProxyWidget(QWidget*self);
MIQT_EXPORT void QWidget_update(QWidget*self);
MIQT_EXPORT void QWidget_repaint(QWidget*self);
MIQT_EXPORT void QWidget_update2(QWidget*self, int x, int y, int w, int h);
MIQT_EXPORT void QWidget_updateWithQRect(QWidget*self, QRect*param1);
MIQT_EXPORT void QWidget_updateWithQRegion(QWidget*self, QRegion*param1);
MIQT_EXPORT void QWidget_repaint2(QWidget*self, int x, int y, int w, int h);
MIQT_EXPORT void QWidget_repaintWithQRect(QWidget*self, QRect*param1);
MIQT_EXPORT void QWidget_repaintWithQRegion(QWidget*self, QRegion*param1);
MIQT_EXPORT void QWidget_setVisible(QWidget*self, bool visible);
MIQT_EXPORT void QWidget_setHidden(QWidget*self, bool hidden);
MIQT_EXPORT void QWidget_show(QWidget*self);
MIQT_EXPORT void QWidget_hide(QWidget*self);
MIQT_EXPORT void QWidget_showMinimized(QWidget*self);
MIQT_EXPORT void QWidget_showMaximized(QWidget*self);
MIQT_EXPORT void QWidget_showFullScreen(QWidget*self);
MIQT_EXPORT void QWidget_showNormal(QWidget*self);
MIQT_EXPORT bool QWidget_close(QWidget*self);
MIQT_EXPORT void QWidget_raise(QWidget*self);
MIQT_EXPORT void QWidget_lower(QWidget*self);
MIQT_EXPORT void QWidget_stackUnder(QWidget*self, QWidget*param1);
MIQT_EXPORT void QWidget_move(QWidget*self, int x, int y);
MIQT_EXPORT void QWidget_moveWithQPoint(QWidget*self, QPoint*param1);
MIQT_EXPORT void QWidget_resize(QWidget*self, int w, int h);
MIQT_EXPORT void QWidget_resizeWithQSize(QWidget*self, QSize*param1);
MIQT_EXPORT void QWidget_setGeometry(QWidget*self, int x, int y, int w, int h);
MIQT_EXPORT void QWidget_setGeometryWithGeometry(QWidget*self, QRect*geometry);
MIQT_EXPORT struct miqt_string QWidget_saveGeometry(QWidget*self);
MIQT_EXPORT bool QWidget_restoreGeometry(QWidget*self, struct miqt_string geometry);
MIQT_EXPORT void QWidget_adjustSize(QWidget*self);
MIQT_EXPORT bool QWidget_isVisible(QWidget*self);
MIQT_EXPORT bool QWidget_isVisibleTo(QWidget*self, QWidget*param1);
MIQT_EXPORT bool QWidget_isHidden(QWidget*self);
MIQT_EXPORT bool QWidget_isMinimized(QWidget*self);
MIQT_EXPORT bool QWidget_isMaximized(QWidget*self);
MIQT_EXPORT bool QWidget_isFullScreen(QWidget*self);
MIQT_EXPORT int QWidget_windowState(QWidget*self);
MIQT_EXPORT void QWidget_setWindowState(QWidget*self, int state);
MIQT_EXPORT void QWidget_overrideWindowState(QWidget*self, int state);
MIQT_EXPORT QSize*QWidget_sizeHint(QWidget*self);
MIQT_EXPORT QSize*QWidget_minimumSizeHint(QWidget*self);
MIQT_EXPORT QSizePolicy*QWidget_sizePolicy(QWidget*self);
MIQT_EXPORT void QWidget_setSizePolicy(QWidget*self, QSizePolicy*sizePolicy);
MIQT_EXPORT void QWidget_setSizePolicy2(QWidget*self, QSizePolicy__Policy*horizontal, QSizePolicy__Policy*vertical);
MIQT_EXPORT int QWidget_heightForWidth(QWidget*self, int param1);
MIQT_EXPORT bool QWidget_hasHeightForWidth(QWidget*self);
MIQT_EXPORT QRegion*QWidget_visibleRegion(QWidget*self);
MIQT_EXPORT void QWidget_setContentsMargins(QWidget*self, int left, int top, int right, int bottom);
MIQT_EXPORT void QWidget_setContentsMarginsWithMargins(QWidget*self, QMargins*margins);
MIQT_EXPORT QMargins*QWidget_contentsMargins(QWidget*self);
MIQT_EXPORT QRect*QWidget_contentsRect(QWidget*self);
MIQT_EXPORT QLayout*QWidget_layout(QWidget*self);
MIQT_EXPORT void QWidget_setLayout(QWidget*self, QLayout*layout);
MIQT_EXPORT void QWidget_updateGeometry(QWidget*self);
MIQT_EXPORT void QWidget_setParent(QWidget*self, QWidget*parent);
MIQT_EXPORT void QWidget_setParent2(QWidget*self, QWidget*parent, Qt_WindowFlags f);
MIQT_EXPORT void QWidget_scroll(QWidget*self, int dx, int dy);
MIQT_EXPORT void QWidget_scroll2(QWidget*self, int dx, int dy, QRect*param3);
MIQT_EXPORT QWidget*QWidget_focusWidget(QWidget*self);
MIQT_EXPORT QWidget*QWidget_nextInFocusChain(QWidget*self);
MIQT_EXPORT QWidget*QWidget_previousInFocusChain(QWidget*self);
MIQT_EXPORT bool QWidget_acceptDrops(QWidget*self);
MIQT_EXPORT void QWidget_setAcceptDrops(QWidget*self, bool on);
MIQT_EXPORT void QWidget_addAction(QWidget*self, QAction*action);
MIQT_EXPORT void QWidget_addActions(QWidget*self, struct miqt_array /* of QAction**/  actions);
MIQT_EXPORT void QWidget_insertActions(QWidget*self, QAction*before, struct miqt_array /* of QAction**/  actions);
MIQT_EXPORT void QWidget_insertAction(QWidget*self, QAction*before, QAction*action);
MIQT_EXPORT void QWidget_removeAction(QWidget*self, QAction*action);
MIQT_EXPORT struct miqt_array /* of QAction**/  QWidget_actions(QWidget*self);
MIQT_EXPORT QAction*QWidget_addActionWithText(QWidget*self, struct miqt_string text);
MIQT_EXPORT QAction*QWidget_addAction2(QWidget*self, QIcon*icon, struct miqt_string text);
MIQT_EXPORT QAction*QWidget_addAction3(QWidget*self, struct miqt_string text, QKeySequence*shortcut);
MIQT_EXPORT QAction*QWidget_addAction4(QWidget*self, QIcon*icon, struct miqt_string text, QKeySequence*shortcut);
MIQT_EXPORT QWidget*QWidget_parentWidget(QWidget*self);
MIQT_EXPORT void QWidget_setWindowFlags(QWidget*self, Qt_WindowFlags type);
MIQT_EXPORT int QWidget_windowFlags(QWidget*self);
MIQT_EXPORT void QWidget_setWindowFlag1(QWidget*self, Qt_WindowType param1);
MIQT_EXPORT void QWidget_overrideWindowFlags(QWidget*self, Qt_WindowFlags type);
MIQT_EXPORT int QWidget_windowType(QWidget*self);
MIQT_EXPORT void QWidget_setWindowFlag(QWidget*self, int param1);
MIQT_EXPORT void QWidget_setWindowFlag2(QWidget*self, int param1, bool on);
MIQT_EXPORT void QWidget_setAttribute2(QWidget*self, Qt_WidgetAttribute param1, bool on);
MIQT_EXPORT QWidget*QWidget_createWindowContainer2(QWindow*window, QWidget*parent);
MIQT_EXPORT QWidget*QWidget_createWindowContainer3(QWindow*window, QWidget*parent, Qt_WindowFlags flags);

MIQT_EXPORT bool QWidget_override_virtual_devType(void*self, intptr_t slot);
MIQT_EXPORT int QWidget_virtualbase_devType(void*self);
MIQT_EXPORT bool QWidget_override_virtual_setVisible(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_setVisible(void*self, bool visible);
MIQT_EXPORT bool QWidget_override_virtual_sizeHint(void*self, intptr_t slot);
MIQT_EXPORT QSize*QWidget_virtualbase_sizeHint(void*self);
MIQT_EXPORT bool QWidget_override_virtual_minimumSizeHint(void*self, intptr_t slot);
MIQT_EXPORT QSize*QWidget_virtualbase_minimumSizeHint(void*self);
MIQT_EXPORT bool QWidget_override_virtual_heightForWidth(void*self, intptr_t slot);
MIQT_EXPORT int QWidget_virtualbase_heightForWidth(void*self, int param1);
MIQT_EXPORT bool QWidget_override_virtual_hasHeightForWidth(void*self, intptr_t slot);
MIQT_EXPORT bool QWidget_virtualbase_hasHeightForWidth(void*self);
MIQT_EXPORT bool QWidget_override_virtual_paintEngine(void*self, intptr_t slot);
MIQT_EXPORT QPaintEngine*QWidget_virtualbase_paintEngine(void*self);
MIQT_EXPORT bool QWidget_override_virtual_event(void*self, intptr_t slot);
MIQT_EXPORT bool QWidget_virtualbase_event(void*self, QEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_mousePressEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_mousePressEvent(void*self, QMouseEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_mouseReleaseEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_mouseReleaseEvent(void*self, QMouseEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_mouseDoubleClickEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_mouseDoubleClickEvent(void*self, QMouseEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_mouseMoveEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_mouseMoveEvent(void*self, QMouseEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_wheelEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_wheelEvent(void*self, QWheelEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_keyPressEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_keyPressEvent(void*self, QKeyEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_keyReleaseEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_keyReleaseEvent(void*self, QKeyEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_focusInEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_focusInEvent(void*self, QFocusEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_focusOutEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_focusOutEvent(void*self, QFocusEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_enterEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_enterEvent(void*self, QEnterEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_leaveEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_leaveEvent(void*self, QEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_paintEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_paintEvent(void*self, QPaintEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_moveEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_moveEvent(void*self, QMoveEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_resizeEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_resizeEvent(void*self, QResizeEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_closeEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_closeEvent(void*self, QCloseEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_contextMenuEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_contextMenuEvent(void*self, QContextMenuEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_tabletEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_tabletEvent(void*self, QTabletEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_actionEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_actionEvent(void*self, QActionEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_dragEnterEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_dragEnterEvent(void*self, QDragEnterEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_dragMoveEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_dragMoveEvent(void*self, QDragMoveEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_dragLeaveEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_dragLeaveEvent(void*self, QDragLeaveEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_dropEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_dropEvent(void*self, QDropEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_showEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_showEvent(void*self, QShowEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_hideEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_hideEvent(void*self, QHideEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_nativeEvent(void*self, intptr_t slot);
MIQT_EXPORT bool QWidget_virtualbase_nativeEvent(void*self, struct miqt_string eventType, void*message, intptr_t*result);
MIQT_EXPORT bool QWidget_override_virtual_changeEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_changeEvent(void*self, QEvent*param1);
MIQT_EXPORT bool QWidget_override_virtual_metric(void*self, intptr_t slot);
MIQT_EXPORT int QWidget_virtualbase_metric(void*self, int param1);
MIQT_EXPORT bool QWidget_override_virtual_initPainter(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_initPainter(void*self, QPainter*painter);
MIQT_EXPORT bool QWidget_override_virtual_redirected(void*self, intptr_t slot);
MIQT_EXPORT QPaintDevice*QWidget_virtualbase_redirected(void*self, QPoint*offset);
MIQT_EXPORT bool QWidget_override_virtual_sharedPainter(void*self, intptr_t slot);
MIQT_EXPORT QPainter*QWidget_virtualbase_sharedPainter(void*self);
MIQT_EXPORT bool QWidget_override_virtual_inputMethodEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_inputMethodEvent(void*self, QInputMethodEvent*param1);
MIQT_EXPORT bool QWidget_override_virtual_inputMethodQuery(void*self, intptr_t slot);
MIQT_EXPORT QVariant*QWidget_virtualbase_inputMethodQuery(void*self, Qt_InputMethodQuery param1);
MIQT_EXPORT bool QWidget_override_virtual_focusNextPrevChild(void*self, intptr_t slot);
MIQT_EXPORT bool QWidget_virtualbase_focusNextPrevChild(void*self, bool next);
MIQT_EXPORT bool QWidget_override_virtual_eventFilter(void*self, intptr_t slot);
MIQT_EXPORT bool QWidget_virtualbase_eventFilter(void*self, QObject*watched, QEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_timerEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_timerEvent(void*self, QTimerEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_childEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_childEvent(void*self, QChildEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_customEvent(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_customEvent(void*self, QEvent*event);
MIQT_EXPORT bool QWidget_override_virtual_connectNotify(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_connectNotify(void*self, QMetaMethod*signal);
MIQT_EXPORT bool QWidget_override_virtual_disconnectNotify(void*self, intptr_t slot);
MIQT_EXPORT void QWidget_virtualbase_disconnectNotify(void*self, QMetaMethod*signal);

MIQT_EXPORT void QWidget_protectedbase_updateMicroFocus(bool*_dynamic_cast_ok, void*self);
MIQT_EXPORT void QWidget_protectedbase_create(bool*_dynamic_cast_ok, void*self);
MIQT_EXPORT void QWidget_protectedbase_destroy(bool*_dynamic_cast_ok, void*self);
MIQT_EXPORT bool QWidget_protectedbase_focusNextChild(bool*_dynamic_cast_ok, void*self);
MIQT_EXPORT bool QWidget_protectedbase_focusPreviousChild(bool*_dynamic_cast_ok, void*self);
MIQT_EXPORT void QWidget_protectedbase_updateMicroFocusWithQuery(bool*_dynamic_cast_ok, void*self, Qt_InputMethodQuery query);
MIQT_EXPORT void QWidget_protectedbase_createWithWId(bool*_dynamic_cast_ok, void*self, WId param1);
MIQT_EXPORT void QWidget_protectedbase_create2(bool*_dynamic_cast_ok, void*self, WId param1, bool initializeWindow);
MIQT_EXPORT void QWidget_protectedbase_create3(bool*_dynamic_cast_ok, void*self, WId param1, bool initializeWindow, bool destroyOldWindow);
MIQT_EXPORT void QWidget_protectedbase_destroyWithDestroyWindow(bool*_dynamic_cast_ok, void*self, bool destroyWindow);
MIQT_EXPORT void QWidget_protectedbase_destroy2(bool*_dynamic_cast_ok, void*self, bool destroyWindow, bool destroySubWindows);
MIQT_EXPORT QObject*QWidget_protectedbase_sender(bool*_dynamic_cast_ok, void*self);
MIQT_EXPORT int QWidget_protectedbase_senderSignalIndex(bool*_dynamic_cast_ok, void*self);
MIQT_EXPORT int QWidget_protectedbase_receivers(bool*_dynamic_cast_ok, void*self, char*signal);
MIQT_EXPORT bool QWidget_protectedbase_isSignalConnected(bool*_dynamic_cast_ok, void*self, QMetaMethod*signal);

MIQT_EXPORT void QWidget_delete(QWidget*self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
